on:
  workflow_dispatch:
  workflow_call:

name: cross-platform

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: ${{ matrix.job.target }} (${{ matrix.job.os }})
    runs-on: ${{ matrix.job.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        job:
          # The OS is used for the runner
          # The target is used by Cargo
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Apple M1 setup
        if: ${{ matrix.job.target == 'aarch64-apple-darwin' }}
        run: |
          echo "SDKROOT=$(xcrun -sdk macosx --show-sdk-path)" >> $GITHUB_ENV
          echo "MACOSX_DEPLOYMENT_TARGET=$(xcrun -sdk macosx --show-sdk-platform-version)" >> $GITHUB_ENV

      - name: Linux ARM setup
        if: ${{ matrix.job.target == 'aarch64-unknown-linux-gnu' }}
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gcc-aarch64-linux-gnu
          echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV

      # For some reason the FFI cheatcode uses WSL bash instead of Git bash, so we need to install a WSL distribution
      - name: Windows setup
        if: ${{ matrix.job.target == 'x86_64-pc-windows-msvc' }}
        run: |
          wsl --install --distribution Ubuntu
        shell: pwsh

      # Required for forge commands that use git
      - name: Setup git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"

      - name: Run tests
        uses: actions-rs/cargo@v1
        if: ${{ matrix.job.target != 'aarch64-apple-darwin' }}
        with:
          use-cross: ${{ matrix.job.use-cross }}
          command: test
          args: --locked --workspace -- --skip fork
