on:
  push:
    branches:
      - master
  pull_request:

name: test

env:
  NEXTEST_EXPERIMENTAL_FILTER_EXPR: 1
  CARGO_TERM_COLOR: always

jobs:
  cross-platform:
    name: Cross-platform tests
    uses: ./.github/workflows/cross-platform.yml

